version: "3"
services:
  web:
    build: .
    entrypoint: ''
    command:
      # Hacky script for quick demonstration purpose
      - bash
      - -c
      - |
        set -o errexit -o nounset -o pipefail
        # Turn on debug so static files will be served
        sed 's/^DEBUG = .*/DEBUG = True/' -i pycontw2016/settings/production.py
        python3 manage.py migrate
        python3 manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    environment:
      # Save us from having to type `--setting=pycontw2016.settings.production`
      DJANGO_SETTINGS_MODULE: pycontw2016.settings.production
      # Plaintext secrets for demonstration purpose
      SECRET_KEY: "asjkh98usd98ufasodfsd198easDLSKFJSDLKFJiojewofijDSFLKJ"
      DATABASE_URL: postgres://pycontw2016:pycontw2016@db:5432/pycontw2016
      # Not sure about these values below
      EMAIL_URL: smtp+tls://username:password@localhost:25
      DSN_URL: http://127.0.0.1/idontknow
    depends_on:
      - db
  db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: pycontw2016
      POSTGRES_USER: pycontw2016
      POSTGRES_PASSWORD: pycontw2016
